### ISSUE TITLE
Minesweeper IS BAD

### ISSUE THREAD

**Issue by Ultrabro-2** [Ultrabro-2/Education-LearningOrg#1]
Although we already have a minesweeper we need a new one. The one that we currently have is awful and is not interesting. The style is bland, there is only one difficulty and a custom game is not available. even if we can't find an authentic copy anything other than that will do. I know a number of really great recreations that we can use and I will post the links to them soon. Minesweeper is one of the more common games that people will want to play and if we continue using this crappy version it might not be as popular. The better quality the games are the more people we will have on the site.

**Comment by 1jammer1** [comment]
I WILL FIX IT

**Comment by 1jammer1** [comment]
reopened as still broken

**Comment by 1jammer1** [comment]
Closed as similar to #2
