### ISSUE TITLE
We need more than crappy online games.

### ISSUE THREAD

**Issue by Ultrabro-2** [Ultrabro-2/Education-LearningOrg#2]
I want to include more than just a sans fight to give more variety to the site when it comes to games. While other sites focus on piling as many crappy mobile games as possible we should work on getting better games. This could include already set up emulated games or have a (.rom) emulator for people to drop their rom files into. this unique quality would put us ahead of the game and make our site more desirable. Don't just add sans ADD UNDERTALE, don't just add Minecraft alpha ADD 1.12.2. We can add anything we want as long as we work on it long enough. I say we make a 1 to 1 copy of Undertale in javascript using the steam files as a reference.

@1jammer1 
@Ultrabro-2

**Comment by 1jammer1** [comment]
WHAT THE HECK how about you redo a java game into javascript and a game without source code too do that ill implement it BUT DONT ASK ME TO PORT A RANDOM GAME also from emulator will be added into secrets

**Comment by 1jammer1** [comment]
Closed with fix of yellow layer with emulator and v86
